export const validateCoupon = (coupon, listing, buyerId) => {
  if (!coupon) {
    return { isValid: false, message: "Coupon not found." };
  }

  if (!coupon.isActive) {
    return { isValid: false, message: "This coupon is inactive." };
  }

  if (coupon.isUsed) {
    return { isValid: false, message: "This coupon has already been used." };
  }

  if (new Date(coupon.expiresAt) < new Date()) {
    return { isValid: false, message: "This coupon has expired." };
  }

  // If coupon is restricted to a specific buyer (e.g., chat coupon generated by seller for buyer)
  if (coupon.buyer && coupon.buyer.toString() !== buyerId.toString()) {
    return { isValid: false, message: "You are not authorized to use this coupon." };
  }

  // If coupon is restricted to a specific listing
  if (coupon.listing && coupon.listing.toString() !== listing._id.toString()) {
    return { isValid: false, message: "This coupon is not valid for this listing." };
  }

  // Check minimum order amount threshold
  if (listing.price < coupon.minOrderAmount) {
    return {
      isValid: false,
      message: `Minimum purchase amount of ₹${coupon.minOrderAmount} not met.`,
    };
  }

  // Calculate discount based on type
  let discount = 0;
  if (coupon.discountType === "percentage") {
    discount = listing.price * (coupon.discountValue / 100);
    if (coupon.maxDiscount && discount > coupon.maxDiscount) {
      discount = coupon.maxDiscount;
    }
  } else {
    // "fixed" amount
    discount = coupon.discountValue;
  }

  // Final price must be at least ₹1
  if (listing.price - discount < 1) {
    discount = Math.max(0, listing.price - 1);
  }

  return {
    isValid: true,
    discountAmount: Math.round(discount),
  };
};
